[tool.poetry]
name = "anki_swiss_knife"
version = "0.1.0"
description = ""
authors = ["Jeff Labonte <grimsleepless@protonmail.com>"]

[tool.pyright]
python.analysis.autoImportCompletions = true

[tool.poetry.dependencies]
python = "^3.8"
google-api-python-client = "^2.19.1"
google-auth-httplib2 = "^0.1.0"
google-auth-oauthlib = "^0.4.6"
boto3 = "^1.18.35"
progressbar2 = "^3.53.1"
xpinyin = "^0.7.6"
requests = "^2.26.0"
beautifulsoup4 = "^4.9.3"
polyglot = "^16.7.4"
PyICU = "^2.7.4"
Morfessor = "^2.0.6"
numpy = "^1.21.1"
pycld2 = "^0.41"
selenium = "^3.141.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
black = "^21.8b0"
pre-commit = "^2.14.1"
neovim = "^0.3.1"
pylint = "^2.10.2"
pytest-testdox = "^2.0.1"
pytest-cov = "^2.12.1"
flake8 = "^3.9.2"
isort = "^5.9.3"
bandit = "^1.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ["py38",]
include = '\.pyi?$'
line-length = 120
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black" 
multi_line_output = 3
